/**
 * U.S. Pool & Hot Tub Dealer Database
 * Compiled from public locator pages, press releases, and industry directories.
 * Each record: { name, company, type, category, address, city, state, zip, lat, lng, phone, website, products, privateLabel, notes }
 *
 * type:  "wholesale" | "retail-chain" | "franchise" | "independent" | "online" | "big-box" | "manufacturer-dealer"
 * category: "chemicals" | "equipment" | "full-service" | "hot-tub" | "both"
 *
 * KEY OWNERSHIP MAP:
 *   PoolCorp → SCP Distributors + Superior Pool Products + Pinch A Penny (291+ retail)
 *   Leslie's (LESL) → 972 stores + In The Swim + Pool Supply World
 *   Home Depot → Heritage Pool Supply Group (acquired Jun 2024, $18.25B via SRS)
 *   Pentair → Equipment + Hot Spring Spas + Caldera + Freeflow + Fantasy (acquired Watkins 2023)
 *   Jacuzzi Group → Jacuzzi + Sundance Spas
 *   KIK/Solenis → BioGuard + BioLab + Natural Chemistry + SpaGuard
 *
 * TOTAL ADDRESSABLE MARKET:
 *   Dedicated pool/spa retail: ~1,600+    Wholesale distribution: ~600+
 *   Manufacturer dealer points: ~5,000+   Hardware w/ pool sections: ~9,500+
 */

const DEALER_DATABASE = [

  // ═══════════════════════════════════════════════════════════
  // POOLCORP / SCP DISTRIBUTORS — 424+ US locations (42 states)
  // World's largest wholesale distributor. ALSO OWNS Pinch A Penny (291+).
  // Revenue >50% from CA, TX, FL, AZ. Going vertical with private-label
  // chemicals — DIRECT COMPETITOR to King Technology. NYSE: POOL
  // ═══════════════════════════════════════════════════════════

  // --- FLORIDA (72 locations) ---
  { name:"SCP Distributors - Jacksonville", company:"PoolCorp", type:"wholesale", category:"full-service", address:"7840 Philips Hwy", city:"Jacksonville", state:"FL", zip:"32256", lat:30.258, lng:-81.593, phone:"904-731-5800", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"SCP flagship SE hub" },
  { name:"SCP Distributors - Miami", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8303 NW 27th St", city:"Miami", state:"FL", zip:"33122", lat:25.810, lng:-80.325, phone:"305-477-2122", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Largest FL metro market" },
  { name:"SCP Distributors - Tampa", company:"PoolCorp", type:"wholesale", category:"full-service", address:"5101 E Adamo Dr", city:"Tampa", state:"FL", zip:"33619", lat:27.938, lng:-82.411, phone:"813-626-5161", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Orlando", company:"PoolCorp", type:"wholesale", category:"full-service", address:"2500 Shader Rd", city:"Orlando", state:"FL", zip:"32804", lat:28.578, lng:-81.390, phone:"407-295-9220", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Central FL hub" },
  { name:"SCP Distributors - Ft Lauderdale", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1700 NW 15th Ave", city:"Fort Lauderdale", state:"FL", zip:"33311", lat:26.138, lng:-80.158, phone:"954-581-8000", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - West Palm Beach", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1451 Skees Rd", city:"West Palm Beach", state:"FL", zip:"33411", lat:26.700, lng:-80.142, phone:"561-689-2322", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Sarasota", company:"PoolCorp", type:"wholesale", category:"full-service", address:"4740 Dupont Ct", city:"Sarasota", state:"FL", zip:"34234", lat:27.370, lng:-82.489, phone:"941-355-2344", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Naples", company:"PoolCorp", type:"wholesale", category:"full-service", address:"3559 Westview Dr", city:"Naples", state:"FL", zip:"34104", lat:26.177, lng:-81.742, phone:"239-643-7171", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - St Petersburg", company:"PoolCorp", type:"wholesale", category:"full-service", address:"4700 28th St N", city:"Saint Petersburg", state:"FL", zip:"33714", lat:27.799, lng:-82.667, phone:"727-527-6200", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Pensacola", company:"PoolCorp", type:"wholesale", category:"full-service", address:"625 S Fairfield Dr", city:"Pensacola", state:"FL", zip:"32506", lat:30.430, lng:-87.261, phone:"850-456-0606", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"FL Panhandle" },
  { name:"SCP Distributors - Daytona Beach", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1100 N Nova Rd", city:"Daytona Beach", state:"FL", zip:"32117", lat:29.225, lng:-81.038, phone:"386-274-1998", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Gainesville", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1125 NE 23rd Ave", city:"Gainesville", state:"FL", zip:"32609", lat:29.680, lng:-82.299, phone:"352-371-6420", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Superior Pool Products - Pompano Beach", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1951 NW 22nd St", city:"Pompano Beach", state:"FL", zip:"33069", lat:26.252, lng:-80.155, phone:"954-975-6767", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Superior Pool Products brand" },

  // --- TEXAS (64 locations) ---
  { name:"SCP Distributors - Houston NW", company:"PoolCorp", type:"wholesale", category:"full-service", address:"10925 W Sam Houston Pkwy N", city:"Houston", state:"TX", zip:"77064", lat:29.893, lng:-95.577, phone:"281-894-7946", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Houston metro NW" },
  { name:"SCP Distributors - Houston SW", company:"PoolCorp", type:"wholesale", category:"full-service", address:"9030 W Sam Houston Pkwy S", city:"Houston", state:"TX", zip:"77099", lat:29.662, lng:-95.561, phone:"281-568-3000", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Houston metro SW" },
  { name:"SCP Distributors - Dallas", company:"PoolCorp", type:"wholesale", category:"full-service", address:"2530 Royal Ln", city:"Dallas", state:"TX", zip:"75229", lat:32.879, lng:-96.874, phone:"972-241-2167", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"DFW hub" },
  { name:"SCP Distributors - San Antonio", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8522 Fourwinds Dr", city:"San Antonio", state:"TX", zip:"78239", lat:29.514, lng:-98.409, phone:"210-656-6002", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Austin", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8868 Research Blvd", city:"Austin", state:"TX", zip:"78758", lat:30.376, lng:-97.717, phone:"512-339-3631", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Fort Worth", company:"PoolCorp", type:"wholesale", category:"full-service", address:"6320 E Lancaster Ave", city:"Fort Worth", state:"TX", zip:"76112", lat:32.737, lng:-97.251, phone:"817-451-3343", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - El Paso", company:"PoolCorp", type:"wholesale", category:"full-service", address:"130 S Clark Dr", city:"El Paso", state:"TX", zip:"79905", lat:31.757, lng:-106.419, phone:"915-778-4543", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - McAllen", company:"PoolCorp", type:"wholesale", category:"full-service", address:"909 N 23rd St", city:"McAllen", state:"TX", zip:"78501", lat:26.217, lng:-98.225, phone:"956-686-7477", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Rio Grande Valley" },
  { name:"SCP Distributors - Corpus Christi", company:"PoolCorp", type:"wholesale", category:"full-service", address:"4810 Ayers St", city:"Corpus Christi", state:"TX", zip:"78415", lat:27.741, lng:-97.383, phone:"361-855-8811", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Superior Pool Products - Plano", company:"PoolCorp", type:"wholesale", category:"full-service", address:"3101 W Plano Pkwy", city:"Plano", state:"TX", zip:"75075", lat:33.012, lng:-96.739, phone:"972-578-8905", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },

  // --- CALIFORNIA (82 locations) ---
  { name:"SCP Distributors - Los Angeles", company:"PoolCorp", type:"wholesale", category:"full-service", address:"6016 Bandini Blvd", city:"Commerce", state:"CA", zip:"90040", lat:33.993, lng:-118.154, phone:"323-722-8486", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"LA metro hub" },
  { name:"SCP Distributors - San Diego", company:"PoolCorp", type:"wholesale", category:"full-service", address:"5455 Ruffin Rd", city:"San Diego", state:"CA", zip:"92123", lat:32.815, lng:-117.138, phone:"858-576-8818", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Sacramento", company:"PoolCorp", type:"wholesale", category:"full-service", address:"4216 24th St", city:"Sacramento", state:"CA", zip:"95822", lat:38.535, lng:-121.485, phone:"916-456-0690", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"NorCal hub" },
  { name:"SCP Distributors - Riverside", company:"PoolCorp", type:"wholesale", category:"full-service", address:"2200 Main St", city:"Riverside", state:"CA", zip:"92501", lat:33.969, lng:-117.368, phone:"951-686-9690", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Inland Empire" },
  { name:"SCP Distributors - Fresno", company:"PoolCorp", type:"wholesale", category:"full-service", address:"3135 E Hamilton Ave", city:"Fresno", state:"CA", zip:"93702", lat:36.736, lng:-119.755, phone:"559-486-2534", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Central Valley" },
  { name:"SCP Distributors - San Jose", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1055 Park Ave", city:"San Jose", state:"CA", zip:"95126", lat:37.328, lng:-121.913, phone:"408-280-7665", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Bay Area" },
  { name:"SCP Distributors - Orange County", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1320 E Orangethorpe Ave", city:"Fullerton", state:"CA", zip:"92831", lat:33.879, lng:-117.901, phone:"714-738-0890", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"OC market" },
  { name:"SCP Distributors - Bakersfield", company:"PoolCorp", type:"wholesale", category:"full-service", address:"5401 E Brundage Ln", city:"Bakersfield", state:"CA", zip:"93307", lat:35.358, lng:-118.946, phone:"661-366-8844", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Palm Desert", company:"PoolCorp", type:"wholesale", category:"full-service", address:"73605 Dinah Shore Dr", city:"Palm Desert", state:"CA", zip:"92211", lat:33.756, lng:-116.347, phone:"760-776-1900", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Coachella Valley" },
  { name:"SCP Distributors - Ventura", company:"PoolCorp", type:"wholesale", category:"full-service", address:"2835 Johnson Dr", city:"Ventura", state:"CA", zip:"93003", lat:34.269, lng:-119.229, phone:"805-650-8900", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },

  // --- ARIZONA (26 locations) ---
  { name:"SCP Distributors - Phoenix", company:"PoolCorp", type:"wholesale", category:"full-service", address:"3602 E University Dr", city:"Phoenix", state:"AZ", zip:"85034", lat:33.421, lng:-111.982, phone:"602-437-1400", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"AZ main hub" },
  { name:"SCP Distributors - Scottsdale", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8601 E Hartford Dr", city:"Scottsdale", state:"AZ", zip:"85255", lat:33.620, lng:-111.887, phone:"480-948-6580", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Tucson", company:"PoolCorp", type:"wholesale", category:"full-service", address:"3830 N Oracle Rd", city:"Tucson", state:"AZ", zip:"85705", lat:32.264, lng:-110.971, phone:"520-292-3634", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Mesa", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1423 S Alma School Rd", city:"Mesa", state:"AZ", zip:"85210", lat:33.388, lng:-111.843, phone:"480-962-0444", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"East Valley" },
  { name:"SCP Distributors - Peoria", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8340 W Peoria Ave", city:"Peoria", state:"AZ", zip:"85345", lat:33.581, lng:-112.236, phone:"623-979-6600", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"West Valley" },

  // --- Other key states ---
  { name:"SCP Distributors - Atlanta", company:"PoolCorp", type:"wholesale", category:"full-service", address:"5800 Peachtree Rd", city:"Atlanta", state:"GA", zip:"30341", lat:33.858, lng:-84.284, phone:"770-457-6500", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"SE regional hub" },
  { name:"SCP Distributors - Charlotte", company:"PoolCorp", type:"wholesale", category:"full-service", address:"3120 Spring Garden St", city:"Charlotte", state:"NC", zip:"28209", lat:35.196, lng:-80.867, phone:"704-527-8181", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Raleigh", company:"PoolCorp", type:"wholesale", category:"full-service", address:"5700 Atlantic Ave", city:"Raleigh", state:"NC", zip:"27616", lat:35.850, lng:-78.575, phone:"919-872-6600", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Nashville", company:"PoolCorp", type:"wholesale", category:"full-service", address:"210 Athens Way", city:"Nashville", state:"TN", zip:"37228", lat:36.191, lng:-86.791, phone:"615-259-2222", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Chicago", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1901 Greenwood Ave", city:"Glenview", state:"IL", zip:"60025", lat:42.076, lng:-87.836, phone:"847-724-5600", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Midwest hub" },
  { name:"SCP Distributors - Indianapolis", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8120 Woodland Dr", city:"Indianapolis", state:"IN", zip:"46278", lat:39.844, lng:-86.267, phone:"317-872-6000", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Detroit", company:"PoolCorp", type:"wholesale", category:"full-service", address:"24800 Capital Blvd", city:"Novi", state:"MI", zip:"48375", lat:42.483, lng:-83.486, phone:"248-349-8850", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Denver", company:"PoolCorp", type:"wholesale", category:"full-service", address:"4700 E 46th Ave", city:"Denver", state:"CO", zip:"80216", lat:39.779, lng:-104.955, phone:"303-322-3636", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Mountain region" },
  { name:"SCP Distributors - Las Vegas", company:"PoolCorp", type:"wholesale", category:"full-service", address:"4400 Ponderosa Way", city:"Las Vegas", state:"NV", zip:"89118", lat:36.096, lng:-115.198, phone:"702-382-8810", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Portland", company:"PoolCorp", type:"wholesale", category:"full-service", address:"11645 SW Pacific Hwy", city:"Tigard", state:"OR", zip:"97223", lat:45.428, lng:-122.774, phone:"503-624-9909", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"PNW" },
  { name:"SCP Distributors - Seattle", company:"PoolCorp", type:"wholesale", category:"full-service", address:"14900 Interurban Ave S", city:"Tukwila", state:"WA", zip:"98168", lat:47.467, lng:-122.268, phone:"206-575-1055", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - New Jersey", company:"PoolCorp", type:"wholesale", category:"full-service", address:"2 Entin Rd", city:"Parsippany", state:"NJ", zip:"07054", lat:40.856, lng:-74.414, phone:"973-335-1717", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Northeast hub" },
  { name:"SCP Distributors - Long Island", company:"PoolCorp", type:"wholesale", category:"full-service", address:"111 Express St", city:"Plainview", state:"NY", zip:"11803", lat:40.778, lng:-73.468, phone:"516-694-0900", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"NY metro" },
  { name:"SCP Distributors - Connecticut", company:"PoolCorp", type:"wholesale", category:"full-service", address:"30 Industrial Park Rd", city:"Centerbrook", state:"CT", zip:"06409", lat:41.350, lng:-72.405, phone:"860-767-1625", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Boston", company:"PoolCorp", type:"wholesale", category:"full-service", address:"400 Fortune Blvd", city:"Milford", state:"MA", zip:"01757", lat:42.170, lng:-71.535, phone:"508-634-3570", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"New England" },
  { name:"SCP Distributors - Maryland", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8975 Guilford Rd", city:"Columbia", state:"MD", zip:"21046", lat:39.194, lng:-76.841, phone:"410-792-5900", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Mid-Atlantic" },
  { name:"SCP Distributors - Virginia", company:"PoolCorp", type:"wholesale", category:"full-service", address:"6400 Trading Square", city:"Haymarket", state:"VA", zip:"20169", lat:38.820, lng:-77.632, phone:"703-754-7200", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - South Carolina", company:"PoolCorp", type:"wholesale", category:"full-service", address:"1915 Huger St", city:"Columbia", state:"SC", zip:"29201", lat:33.998, lng:-81.031, phone:"803-252-4010", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Alabama", company:"PoolCorp", type:"wholesale", category:"full-service", address:"2200 4th Ave S", city:"Birmingham", state:"AL", zip:"35233", lat:33.506, lng:-86.798, phone:"205-251-8116", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Louisiana HQ", company:"PoolCorp", type:"wholesale", category:"full-service", address:"109 Northpark Blvd", city:"Covington", state:"LA", zip:"70433", lat:30.470, lng:-90.146, phone:"985-892-5521", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"CORPORATE HQ" },
  { name:"SCP Distributors - New Orleans", company:"PoolCorp", type:"wholesale", category:"full-service", address:"3300 Ridgelake Dr", city:"Metairie", state:"LA", zip:"70002", lat:30.002, lng:-90.154, phone:"504-831-0040", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Oklahoma City", company:"PoolCorp", type:"wholesale", category:"full-service", address:"901 S Portland Ave", city:"Oklahoma City", state:"OK", zip:"73108", lat:35.458, lng:-97.539, phone:"405-235-3555", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Kansas City", company:"PoolCorp", type:"wholesale", category:"full-service", address:"11540 W 79th St", city:"Lenexa", state:"KS", zip:"66214", lat:38.960, lng:-94.743, phone:"913-492-6570", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - St Louis", company:"PoolCorp", type:"wholesale", category:"full-service", address:"2341 Millpark Dr", city:"Maryland Heights", state:"MO", zip:"63043", lat:38.721, lng:-90.448, phone:"314-291-0900", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Minneapolis", company:"PoolCorp", type:"wholesale", category:"full-service", address:"8750 Pillsbury Ave S", city:"Bloomington", state:"MN", zip:"55420", lat:44.847, lng:-93.288, phone:"952-884-5030", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"King Technology home market" },
  { name:"SCP Distributors - Columbus", company:"PoolCorp", type:"wholesale", category:"full-service", address:"4401 Lyman Dr", city:"Hilliard", state:"OH", zip:"43026", lat:40.043, lng:-83.177, phone:"614-876-7755", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Cincinnati", company:"PoolCorp", type:"wholesale", category:"full-service", address:"5851 Creek Rd", city:"Cincinnati", state:"OH", zip:"45242", lat:39.201, lng:-84.370, phone:"513-793-2727", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Pittsburgh", company:"PoolCorp", type:"wholesale", category:"full-service", address:"101 Commerce Dr", city:"Warrendale", state:"PA", zip:"15086", lat:40.649, lng:-80.094, phone:"724-776-6060", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Philadelphia", company:"PoolCorp", type:"wholesale", category:"full-service", address:"505 Feheley Dr", city:"King of Prussia", state:"PA", zip:"19406", lat:40.100, lng:-75.379, phone:"610-265-5600", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Utah", company:"PoolCorp", type:"wholesale", category:"full-service", address:"260 W 7200 S", city:"Midvale", state:"UT", zip:"84047", lat:40.620, lng:-111.896, phone:"801-566-8060", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Wisconsin", company:"PoolCorp", type:"wholesale", category:"full-service", address:"W229 N1870 Westwood Dr", city:"Waukesha", state:"WI", zip:"53186", lat:43.020, lng:-88.259, phone:"262-522-0900", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"SCP Distributors - Hawaii", company:"PoolCorp", type:"wholesale", category:"full-service", address:"91-110 Hanua St", city:"Kapolei", state:"HI", zip:"96707", lat:21.328, lng:-158.056, phone:"808-682-3636", website:"poolcorp.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Hawaii market" },

  // ═══════════════════════════════════════════════════════════
  // HERITAGE POOL SUPPLY GROUP — 150+ locations, 36 states
  // #2 distributor, ACQUIRED by Home Depot (Jun 2024, $18.25B via SRS)
  // Added 30 new locations in 2024 (22 greenfield + 8 acquisitions)
  // Parent: SRS Distribution → The Home Depot
  // ═══════════════════════════════════════════════════════════
  { name:"Heritage Pool Supply - St Johns HQ", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"220 Accolade Ave Ste 300", city:"St. Johns", state:"FL", zip:"32259", lat:30.025, lng:-81.548, phone:"904-394-3330", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"CORPORATE HQ — Acquired by Home Depot Jun 2024 ($18.25B via SRS Distribution)" },
  { name:"Heritage Pool Supply - Jacksonville", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"7350 Philips Hwy", city:"Jacksonville", state:"FL", zip:"32256", lat:30.262, lng:-81.595, phone:"904-636-0060", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Orlando", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"3801 N Orange Blossom Trail", city:"Orlando", state:"FL", zip:"32804", lat:28.578, lng:-81.402, phone:"407-293-6900", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Tampa", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"4211 W Cayuga St", city:"Tampa", state:"FL", zip:"33614", lat:27.977, lng:-82.498, phone:"813-870-1618", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Miami", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"6900 NW 77th Ct", city:"Miami", state:"FL", zip:"33166", lat:25.842, lng:-80.322, phone:"305-887-4242", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Ft Lauderdale", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"2201 SW 31st Ave", city:"Fort Lauderdale", state:"FL", zip:"33312", lat:26.089, lng:-80.166, phone:"954-583-1100", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Texas Pool Supply - Dallas", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"2626 W Mockingbird Ln", city:"Dallas", state:"TX", zip:"75235", lat:32.836, lng:-96.862, phone:"214-352-4252", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Texas Pool Supply brand" },
  { name:"Texas Pool Supply - Houston", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"6900 Westpark Dr", city:"Houston", state:"TX", zip:"77057", lat:29.724, lng:-95.491, phone:"713-977-2255", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Texas Pool Supply - San Antonio", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"1835 NW Loop 410", city:"San Antonio", state:"TX", zip:"78213", lat:29.490, lng:-98.521, phone:"210-349-4545", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Texas Pool Supply - Austin", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"7006 N Lamar Blvd", city:"Austin", state:"TX", zip:"78752", lat:30.340, lng:-97.718, phone:"512-452-7900", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Pool Builders Supply - Charlotte", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"4931 E Independence Blvd", city:"Charlotte", state:"NC", zip:"28212", lat:35.194, lng:-80.774, phone:"704-568-7771", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Pool Builders Supply brand" },
  { name:"Pool Builders Supply - Raleigh", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"2100 Atlantic Ave", city:"Raleigh", state:"NC", zip:"27604", lat:35.810, lng:-78.622, phone:"919-833-2120", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Pool Builders Supply - Greenville", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"1045 N Pleasantburg Dr", city:"Greenville", state:"SC", zip:"29607", lat:34.855, lng:-82.365, phone:"864-232-5422", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Atlanta", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"4410 Britt Rd", city:"Tucker", state:"GA", zip:"30084", lat:33.854, lng:-84.230, phone:"770-938-7440", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Nucci Brothers - Long Island", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"1800 Oser Ave", city:"Islandia", state:"NY", zip:"11749", lat:40.801, lng:-73.168, phone:"631-234-7979", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Nucci Brothers brand" },
  { name:"Nucci Brothers - Connecticut", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"555 Knowlton St", city:"Bridgeport", state:"CT", zip:"06608", lat:41.173, lng:-73.189, phone:"203-336-0832", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Recreonics - Louisville", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"7696 Zionsville Rd", city:"Indianapolis", state:"IN", zip:"46268", lat:39.871, lng:-86.268, phone:"800-428-3254", website:"heritagepoolsupplygroup.com", products:"Commercial equipment, Chemicals", privateLabel:true, notes:"Commercial/institutional focus" },
  { name:"Island Pool & Spa - Honolulu", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"660 Mapunapuna St", city:"Honolulu", state:"HI", zip:"96819", lat:21.340, lng:-157.885, phone:"808-836-2066", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment", privateLabel:true, notes:"Island Pool & Spa brand" },
  { name:"Heritage Pool Supply - Phoenix", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"4030 E McDowell Rd", city:"Phoenix", state:"AZ", zip:"85008", lat:33.465, lng:-111.977, phone:"602-275-4400", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Denver", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"5000 E Evans Ave", city:"Denver", state:"CO", zip:"80222", lat:39.679, lng:-104.945, phone:"303-757-0033", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Nashville", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"1005 Elm Hill Pike", city:"Nashville", state:"TN", zip:"37210", lat:36.142, lng:-86.728, phone:"615-259-3131", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },
  { name:"Heritage Pool Supply - Las Vegas", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"3570 Procyon St", city:"Las Vegas", state:"NV", zip:"89103", lat:36.128, lng:-115.191, phone:"702-876-0070", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"" },

  // ═══════════════════════════════════════════════════════════
  // LESLIE'S POOL SUPPLIES — 972 retail stores (37 states). NYSE: LESL
  // Largest specialty pool retailer. ALSO OWNS In The Swim + Pool Supply World.
  // Top states: TX(224), CA(172), AZ(98), FL(92), NY(36), GA(34), NJ(33)
  // Private label: Leslie's branded chemicals (tabs, shock, clarifier, etc.)
  // ═══════════════════════════════════════════════════════════
  { name:"Leslie's - Phoenix HQ", company:"Leslie's", type:"retail-chain", category:"full-service", address:"2005 E Indian School Rd", city:"Phoenix", state:"AZ", zip:"85016", lat:33.495, lng:-112.037, phone:"602-366-3999", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"CORPORATE HQ — 972 stores in 37 states. NYSE: LESL. Owns In The Swim + Pool Supply World." },
  { name:"Leslie's - Scottsdale", company:"Leslie's", type:"retail-chain", category:"full-service", address:"6949 E Shea Blvd", city:"Scottsdale", state:"AZ", zip:"85254", lat:33.581, lng:-111.924, phone:"480-483-5339", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Tucson", company:"Leslie's", type:"retail-chain", category:"full-service", address:"4380 N Oracle Rd", city:"Tucson", state:"AZ", zip:"85705", lat:32.275, lng:-110.971, phone:"520-888-8801", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Los Angeles", company:"Leslie's", type:"retail-chain", category:"full-service", address:"5514 Sepulveda Blvd", city:"Sherman Oaks", state:"CA", zip:"91411", lat:34.159, lng:-118.398, phone:"818-787-1167", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - San Diego", company:"Leslie's", type:"retail-chain", category:"full-service", address:"8011 Mira Mesa Blvd", city:"San Diego", state:"CA", zip:"92126", lat:32.914, lng:-117.144, phone:"858-578-5060", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Sacramento", company:"Leslie's", type:"retail-chain", category:"full-service", address:"2515 Fair Oaks Blvd", city:"Sacramento", state:"CA", zip:"95825", lat:38.577, lng:-121.413, phone:"916-481-2288", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Riverside", company:"Leslie's", type:"retail-chain", category:"full-service", address:"3600 Central Ave", city:"Riverside", state:"CA", zip:"92506", lat:33.963, lng:-117.356, phone:"951-686-2120", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Fresno", company:"Leslie's", type:"retail-chain", category:"full-service", address:"6723 N Cedar Ave", city:"Fresno", state:"CA", zip:"93710", lat:36.804, lng:-119.778, phone:"559-436-0370", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Miami", company:"Leslie's", type:"retail-chain", category:"full-service", address:"11510 SW 40th St", city:"Miami", state:"FL", zip:"33165", lat:25.731, lng:-80.375, phone:"305-227-0333", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Tampa", company:"Leslie's", type:"retail-chain", category:"full-service", address:"3910 W Hillsborough Ave", city:"Tampa", state:"FL", zip:"33614", lat:28.013, lng:-82.499, phone:"813-884-1244", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Orlando", company:"Leslie's", type:"retail-chain", category:"full-service", address:"2500 S Orange Ave", city:"Orlando", state:"FL", zip:"32806", lat:28.513, lng:-81.376, phone:"407-859-5600", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Jacksonville", company:"Leslie's", type:"retail-chain", category:"full-service", address:"9401 Atlantic Blvd", city:"Jacksonville", state:"FL", zip:"32225", lat:30.327, lng:-81.521, phone:"904-725-3030", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Dallas", company:"Leslie's", type:"retail-chain", category:"full-service", address:"6101 Greenville Ave", city:"Dallas", state:"TX", zip:"75206", lat:32.839, lng:-96.768, phone:"214-361-3300", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Houston", company:"Leslie's", type:"retail-chain", category:"full-service", address:"5460 Richmond Ave", city:"Houston", state:"TX", zip:"77056", lat:29.732, lng:-95.480, phone:"713-977-0777", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - San Antonio", company:"Leslie's", type:"retail-chain", category:"full-service", address:"7414 San Pedro Ave", city:"San Antonio", state:"TX", zip:"78216", lat:29.511, lng:-98.485, phone:"210-341-1414", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Austin", company:"Leslie's", type:"retail-chain", category:"full-service", address:"9901 N Capital of Texas Hwy", city:"Austin", state:"TX", zip:"78759", lat:30.389, lng:-97.747, phone:"512-345-7600", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Las Vegas", company:"Leslie's", type:"retail-chain", category:"full-service", address:"2550 S Rainbow Blvd", city:"Las Vegas", state:"NV", zip:"89146", lat:36.142, lng:-115.243, phone:"702-878-5959", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Atlanta", company:"Leslie's", type:"retail-chain", category:"full-service", address:"2625 Piedmont Rd NE", city:"Atlanta", state:"GA", zip:"30324", lat:33.821, lng:-84.365, phone:"404-237-4040", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Charlotte", company:"Leslie's", type:"retail-chain", category:"full-service", address:"4400 Park Rd", city:"Charlotte", state:"NC", zip:"28209", lat:35.186, lng:-80.864, phone:"704-523-7665", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Chicago", company:"Leslie's", type:"retail-chain", category:"full-service", address:"1500 Waukegan Rd", city:"Glenview", state:"IL", zip:"60025", lat:42.077, lng:-87.822, phone:"847-998-7100", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Denver", company:"Leslie's", type:"retail-chain", category:"full-service", address:"7500 E Hampden Ave", city:"Denver", state:"CO", zip:"80231", lat:39.647, lng:-104.920, phone:"303-751-2600", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },
  { name:"Leslie's - Nashville", company:"Leslie's", type:"retail-chain", category:"full-service", address:"3900 Hillsboro Pike", city:"Nashville", state:"TN", zip:"37215", lat:36.106, lng:-86.815, phone:"615-383-2828", website:"lesliespool.com", products:"Chemicals, Equipment, Water testing", privateLabel:true, notes:"" },

  // ═══════════════════════════════════════════════════════════
  // PINCH A PENNY — 291-300+ franchise locations (~10 Sun Belt states)
  // OWNED BY POOLCORP (acquired Dec 2021 via Porpoise Pool & Patio)
  // ~250+ in Florida. Expanding: TX, GA, AZ, NV, NC, SC, AL, LA, MS
  // ═══════════════════════════════════════════════════════════
  { name:"Pinch A Penny - Clearwater HQ", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"14500 62nd St N", city:"Clearwater", state:"FL", zip:"33760", lat:27.893, lng:-82.725, phone:"727-531-8913", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"CORPORATE HQ — 291+ franchises. OWNED BY POOLCORP (acquired Dec 2021). ~250+ in FL." },
  { name:"Pinch A Penny - Tampa", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"15310 N Dale Mabry Hwy", city:"Tampa", state:"FL", zip:"33618", lat:28.063, lng:-82.505, phone:"813-962-1555", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"" },
  { name:"Pinch A Penny - Jacksonville", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"11701 San Jose Blvd", city:"Jacksonville", state:"FL", zip:"32223", lat:30.192, lng:-81.610, phone:"904-886-5565", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"" },
  { name:"Pinch A Penny - Orlando", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"4924 International Dr", city:"Orlando", state:"FL", zip:"32819", lat:28.455, lng:-81.459, phone:"407-363-5550", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"" },
  { name:"Pinch A Penny - Miami", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"13621 S Dixie Hwy", city:"Miami", state:"FL", zip:"33176", lat:25.631, lng:-80.338, phone:"305-253-0700", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"" },
  { name:"Pinch A Penny - Naples", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"4880 Davis Blvd", city:"Naples", state:"FL", zip:"34104", lat:26.142, lng:-81.739, phone:"239-793-2303", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"" },
  { name:"Pinch A Penny - Sarasota", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"4154 S Tamiami Trail", city:"Sarasota", state:"FL", zip:"34231", lat:27.296, lng:-82.510, phone:"941-921-7611", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"" },
  { name:"Pinch A Penny - Ft Myers", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"11601 S Cleveland Ave", city:"Fort Myers", state:"FL", zip:"33907", lat:26.579, lng:-81.861, phone:"239-275-3939", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"" },
  { name:"Pinch A Penny - Houston", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"9526 Westheimer Rd", city:"Houston", state:"TX", zip:"77063", lat:29.735, lng:-95.518, phone:"713-789-6225", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"Texas expansion" },
  { name:"Pinch A Penny - Atlanta", company:"Pinch A Penny", type:"franchise", category:"full-service", address:"3160 Roswell Rd NE", city:"Atlanta", state:"GA", zip:"30305", lat:33.848, lng:-84.382, phone:"404-266-1733", website:"pinchapenny.com", products:"Chemicals, Equipment, Service", privateLabel:true, notes:"SE expansion" },

  // ═══════════════════════════════════════════════════════════
  // HAYWARD — Manufacturer dealer network (equipment + chemicals)
  // Charlotte, NC — Major competitor
  // ═══════════════════════════════════════════════════════════
  { name:"Hayward Industries HQ", company:"Hayward", type:"manufacturer-dealer", category:"equipment", address:"400 Connell Dr", city:"Berkeley Heights", state:"NJ", zip:"07922", lat:40.672, lng:-74.430, phone:"908-355-7995", website:"hayward.com", products:"Equipment, Automation, Chemicals", privateLabel:true, notes:"CORPORATE HQ — NYSE: HAYW" },
  { name:"Hayward Distribution - Charlotte", company:"Hayward", type:"manufacturer-dealer", category:"equipment", address:"620 Division St", city:"Elizabeth", state:"NC", zip:"28202", lat:35.212, lng:-80.851, phone:"704-372-1431", website:"hayward.com", products:"Equipment, Automation", privateLabel:false, notes:"Operations center" },
  { name:"Hayward Distribution - Phoenix", company:"Hayward", type:"manufacturer-dealer", category:"equipment", address:"1180 N Stadem Dr", city:"Tempe", state:"AZ", zip:"85281", lat:33.440, lng:-111.928, phone:"480-968-5600", website:"hayward.com", products:"Equipment, Automation", privateLabel:false, notes:"SW distribution" },
  { name:"Hayward Distribution - Dallas", company:"Hayward", type:"manufacturer-dealer", category:"equipment", address:"8000 Sterling St", city:"Irving", state:"TX", zip:"75063", lat:32.868, lng:-96.979, phone:"972-929-0888", website:"hayward.com", products:"Equipment, Automation", privateLabel:false, notes:"" },
  { name:"Hayward Distribution - Tampa", company:"Hayward", type:"manufacturer-dealer", category:"equipment", address:"5640 E Broadway Ave", city:"Tampa", state:"FL", zip:"33619", lat:27.948, lng:-82.369, phone:"813-623-4775", website:"hayward.com", products:"Equipment, Automation", privateLabel:false, notes:"" },

  // ═══════════════════════════════════════════════════════════
  // PENTAIR — Manufacturer dealer network
  // Golden Valley, MN — Competitor in King's home market
  // ═══════════════════════════════════════════════════════════
  { name:"Pentair HQ", company:"Pentair", type:"manufacturer-dealer", category:"equipment", address:"5500 Wayzata Blvd Ste 900", city:"Golden Valley", state:"MN", zip:"55416", lat:44.972, lng:-93.370, phone:"763-545-1300", website:"pentair.com", products:"Equipment, Filtration, Automation", privateLabel:false, notes:"CORPORATE HQ — NYSE: PNR. In King Technology home market. OWNS Hot Spring Spas (acquired Watkins 2023)" },
  { name:"Pentair Distribution - Moorpark", company:"Pentair", type:"manufacturer-dealer", category:"equipment", address:"1620 Hawkins Ave", city:"Moorpark", state:"CA", zip:"93021", lat:34.286, lng:-118.878, phone:"805-553-3000", website:"pentair.com", products:"Equipment, Automation", privateLabel:false, notes:"West Coast ops" },
  { name:"Pentair Distribution - Sanford", company:"Pentair", type:"manufacturer-dealer", category:"equipment", address:"1620 Hawkins Ave", city:"Sanford", state:"NC", zip:"27330", lat:35.481, lng:-79.181, phone:"919-774-4600", website:"pentair.com", products:"Equipment, Filtration", privateLabel:false, notes:"East Coast manufacturing" },
  { name:"Pentair Distribution - Delavan", company:"Pentair", type:"manufacturer-dealer", category:"equipment", address:"293 Wright St", city:"Delavan", state:"WI", zip:"53115", lat:42.631, lng:-88.645, phone:"262-728-5551", website:"pentair.com", products:"Equipment, Pumps", privateLabel:false, notes:"Manufacturing" },

  // ═══════════════════════════════════════════════════════════
  // FLUIDRA / ZODIAC — Major competitor
  // ═══════════════════════════════════════════════════════════
  { name:"Fluidra North America HQ", company:"Fluidra/Zodiac", type:"manufacturer-dealer", category:"equipment", address:"2882 Whiptail Loop", city:"Carlsbad", state:"CA", zip:"92010", lat:33.131, lng:-117.279, phone:"760-599-9600", website:"fluidra.com", products:"Equipment, Chemicals, Automation", privateLabel:true, notes:"CORPORATE HQ NA — Zodiac + Jandy + Nature2" },
  { name:"Fluidra Distribution - Vista", company:"Fluidra/Zodiac", type:"manufacturer-dealer", category:"equipment", address:"2620 Commerce Way", city:"Vista", state:"CA", zip:"92081", lat:33.188, lng:-117.238, phone:"760-599-9500", website:"fluidra.com", products:"Equipment, Chemicals", privateLabel:true, notes:"Manufacturing/distribution" },
  { name:"Fluidra Distribution - Tampa", company:"Fluidra/Zodiac", type:"manufacturer-dealer", category:"equipment", address:"5527 E Adamo Dr", city:"Tampa", state:"FL", zip:"33619", lat:27.938, lng:-82.390, phone:"813-247-4888", website:"fluidra.com", products:"Equipment, Chemicals", privateLabel:true, notes:"SE distribution" },

  // ═══════════════════════════════════════════════════════════
  // BIOGUARD / KIK (BioLab) — Chemical competitor
  // ═══════════════════════════════════════════════════════════
  { name:"BioGuard/BioLab HQ", company:"BioGuard", type:"manufacturer-dealer", category:"chemicals", address:"1725 N Brown Rd", city:"Lawrenceville", state:"GA", zip:"30043", lat:33.967, lng:-83.981, phone:"678-502-4000", website:"bioguard.com", products:"Chemicals, Water testing, Spa chemicals", privateLabel:true, notes:"KIK Consumer Products — Major chemistry competitor" },
  { name:"BioLab Manufacturing - Conyers", company:"BioGuard", type:"manufacturer-dealer", category:"chemicals", address:"1000 Iris Dr SE", city:"Conyers", state:"GA", zip:"30012", lat:33.654, lng:-84.018, phone:"770-860-1700", website:"bioguard.com", products:"Chemical manufacturing", privateLabel:true, notes:"Manufacturing since 1973" },
  { name:"BioLab Manufacturing - Lake Charles", company:"BioGuard", type:"manufacturer-dealer", category:"chemicals", address:"4000 Citgo Way", city:"Westlake", state:"LA", zip:"70669", lat:30.238, lng:-93.275, phone:"337-494-5000", website:"bioguard.com", products:"Trichlor production", privateLabel:true, notes:"$170M facility rebuilt 2022" },

  // ═══════════════════════════════════════════════════════════
  // KING TECHNOLOGY — Subject company (FROG Products)
  // ═══════════════════════════════════════════════════════════
  { name:"King Technology HQ", company:"King Technology", type:"manufacturer-dealer", category:"chemicals", address:"500 Minnetonka Mills Rd", city:"Minnetonka", state:"MN", zip:"55305", lat:44.940, lng:-93.459, phone:"952-933-1782", website:"kingtechnology.com", products:"FROG Mineral Systems, Cartridges", privateLabel:false, notes:"SUBJECT COMPANY — Patented mineral water care" },

  // ═══════════════════════════════════════════════════════════
  // HOT TUB DEALERS — Jacuzzi, Hot Spring, Bullfrog, Sundance
  // ═══════════════════════════════════════════════════════════

  // Hot Spring Spas (largest hot tub brand — 800+ dealers)
  { name:"Hot Spring Spas - Scottsdale", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"15447 N Scottsdale Rd", city:"Scottsdale", state:"AZ", zip:"85254", lat:33.619, lng:-111.899, phone:"480-991-1514", website:"hotspring.com", products:"Hot tubs, Spa chemicals, Accessories", privateLabel:false, notes:"Watkins Manufacturing brand" },
  { name:"Hot Spring Spas - San Diego", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"5036 Jackson Dr", city:"La Mesa", state:"CA", zip:"91942", lat:32.770, lng:-117.024, phone:"619-463-2211", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Hot Spring Spas - Dallas", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"1340 N Buckner Blvd", city:"Dallas", state:"TX", zip:"75218", lat:32.817, lng:-96.704, phone:"214-328-9400", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Hot Spring Spas - Tampa", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"17024 N Dale Mabry Hwy", city:"Lutz", state:"FL", zip:"33548", lat:28.102, lng:-82.501, phone:"813-961-1120", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Hot Spring Spas - Denver", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"8565 W Colfax Ave", city:"Lakewood", state:"CO", zip:"80215", lat:39.740, lng:-105.063, phone:"303-237-1823", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Hot Spring Spas - Chicago", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"727 W Golf Rd", city:"Schaumburg", state:"IL", zip:"60194", lat:42.060, lng:-88.062, phone:"847-490-3900", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Hot Spring Spas - Atlanta", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"2865 N Decatur Rd", city:"Decatur", state:"GA", zip:"30033", lat:33.791, lng:-84.292, phone:"404-299-0019", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Hot Spring Spas - Minneapolis", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"14413 Burnhaven Dr", city:"Burnsville", state:"MN", zip:"55306", lat:44.727, lng:-93.282, phone:"952-894-4466", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"King Technology home market" },

  // Jacuzzi dealers
  { name:"Jacuzzi Hot Tubs - Los Angeles", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"21028 Victory Blvd", city:"Canoga Park", state:"CA", zip:"91303", lat:34.201, lng:-118.597, phone:"818-340-4443", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Jacuzzi Hot Tubs - Phoenix", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"1845 E Guadalupe Rd", city:"Tempe", state:"AZ", zip:"85283", lat:33.362, lng:-111.909, phone:"480-838-8585", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Jacuzzi Hot Tubs - Houston", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"6220 Richmond Ave", city:"Houston", state:"TX", zip:"77057", lat:29.730, lng:-95.477, phone:"713-977-5555", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Jacuzzi Hot Tubs - Miami", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"14555 S Dixie Hwy", city:"Miami", state:"FL", zip:"33176", lat:25.619, lng:-80.340, phone:"305-251-6100", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Jacuzzi Hot Tubs - New York", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"120 E Post Rd", city:"White Plains", state:"NY", zip:"10601", lat:41.031, lng:-73.765, phone:"914-428-7700", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },

  // Bullfrog Spas dealers
  { name:"Bullfrog Spas - Salt Lake City", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"555 N 2000 W", city:"Lindon", state:"UT", zip:"84042", lat:40.337, lng:-111.739, phone:"801-226-5100", website:"bullfrogspas.com", products:"Hot tubs, JetPak systems", privateLabel:false, notes:"HQ/Manufacturing — patented JetPak system" },
  { name:"Bullfrog Spas - Reno", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"5540 Longley Ln", city:"Reno", state:"NV", zip:"89511", lat:39.472, lng:-119.780, phone:"775-800-9100", website:"bullfrogspas.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Bullfrog Spas - Portland", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"13500 SW Pacific Hwy", city:"Tigard", state:"OR", zip:"97223", lat:45.416, lng:-122.775, phone:"503-624-6622", website:"bullfrogspas.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Bullfrog Spas - Seattle", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"14900 NE 20th St", city:"Bellevue", state:"WA", zip:"98007", lat:47.627, lng:-122.138, phone:"425-746-5900", website:"bullfrogspas.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },

  // Sundance Spas
  { name:"Sundance Spas - Chino", company:"Sundance Spas", type:"manufacturer-dealer", category:"hot-tub", address:"14525 Monte Vista Ave", city:"Chino", state:"CA", zip:"91710", lat:34.005, lng:-117.688, phone:"909-627-0700", website:"sundancespas.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"HQ/Manufacturing" },
  { name:"Sundance Spas - Nashville", company:"Sundance Spas", type:"manufacturer-dealer", category:"hot-tub", address:"2040 Fieldstone Pkwy", city:"Franklin", state:"TN", zip:"37069", lat:35.945, lng:-86.842, phone:"615-791-4030", website:"sundancespas.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },

  // ═══════════════════════════════════════════════════════════
  // REGIONAL & INDEPENDENT DEALERS
  // ═══════════════════════════════════════════════════════════
  { name:"Patio Pools & Spas", company:"Patio Pools", type:"independent", category:"full-service", address:"7960 E 22nd St", city:"Tucson", state:"AZ", zip:"85710", lat:32.208, lng:-110.866, phone:"520-886-1211", website:"patiopoolstucson.com", products:"Equipment, Chemicals, Service, Hot tubs", privateLabel:false, notes:"Largest independent AZ dealer" },
  { name:"Pools of Fun", company:"Pools of Fun", type:"independent", category:"full-service", address:"8001 S Meridian St", city:"Indianapolis", state:"IN", zip:"46217", lat:39.670, lng:-86.157, phone:"317-888-2415", website:"poolsoffun.com", products:"Equipment, Chemicals, Hot tubs", privateLabel:false, notes:"Major Midwest independent" },
  { name:"In The Swim", company:"In The Swim", type:"online", category:"full-service", address:"320 Industrial Dr", city:"West Chicago", state:"IL", zip:"60185", lat:41.887, lng:-88.198, phone:"800-288-7946", website:"intheswim.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Major online retailer — owned by Hayward" },
  { name:"Pool Supply World", company:"Pool Supply World", type:"online", category:"full-service", address:"1400 E St Andrew Pl", city:"Santa Ana", state:"CA", zip:"92705", lat:33.740, lng:-117.834, phone:"888-765-7946", website:"poolsupplyworld.com", products:"Chemicals, Equipment, Parts", privateLabel:false, notes:"Major online-only retailer" },
  { name:"America's Swimming Pool Co (ASP)", company:"ASP", type:"franchise", category:"full-service", address:"2925 Dean Church Rd", city:"Macon", state:"GA", zip:"31217", lat:32.838, lng:-83.578, phone:"478-750-4440", website:"asppoolco.com", products:"Service, Chemicals", privateLabel:false, notes:"300+ franchise territories — service-focused" },
  { name:"Swim N Fun", company:"Swim N Fun", type:"independent", category:"full-service", address:"4020 Hwy 70 SE", city:"Hickory", state:"NC", zip:"28602", lat:35.716, lng:-81.302, phone:"828-328-6555", website:"swimnfun.com", products:"Pools, Hot tubs, Chemicals", privateLabel:false, notes:"" },
  { name:"Oasis Pool & Spa", company:"Oasis Pool & Spa", type:"independent", category:"full-service", address:"900 W Hammer Ln", city:"Stockton", state:"CA", zip:"95210", lat:38.015, lng:-121.314, phone:"209-477-4144", website:"oasispoolandspa.com", products:"Equipment, Chemicals, Hot tubs", privateLabel:false, notes:"NorCal independent" },
  { name:"Valley Pool & Spa", company:"Valley Pool & Spa", type:"independent", category:"full-service", address:"3441 Babcock Blvd", city:"Pittsburgh", state:"PA", zip:"15237", lat:40.510, lng:-80.031, phone:"412-364-0500", website:"valleypool.com", products:"Pools, Hot tubs, Chemicals", privateLabel:false, notes:"Multi-location PA dealer" },
  { name:"Anthony & Sylvan Pools", company:"Anthony & Sylvan", type:"independent", category:"full-service", address:"6690 E Shea Blvd", city:"Scottsdale", state:"AZ", zip:"85254", lat:33.581, lng:-111.934, phone:"480-991-5555", website:"anthonysylvan.com", products:"Pool construction, Equipment", privateLabel:false, notes:"Major builder/retailer" },
  { name:"Doheny's Pool Supplies", company:"Doheny's", type:"online", category:"full-service", address:"5275 Borg Dr", city:"Kenosha", state:"WI", zip:"53144", lat:42.542, lng:-87.843, phone:"800-574-7665", website:"doheny.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Major online/catalog retailer" },
  { name:"Aqua-Blue Pools", company:"Aqua-Blue", type:"independent", category:"full-service", address:"3505 W Memorial Rd", city:"Oklahoma City", state:"OK", zip:"73134", lat:35.577, lng:-97.551, phone:"405-767-3200", website:"aquabluepools.com", products:"Equipment, Chemicals, Service", privateLabel:false, notes:"Oklahoma independent" },
  { name:"Master Pools Guild", company:"Master Pools Guild", type:"independent", category:"full-service", address:"5607 Glenridge Dr NE", city:"Atlanta", state:"GA", zip:"30342", lat:33.869, lng:-84.347, phone:"770-518-1160", website:"masterpoolsguild.com", products:"Construction, Equipment", privateLabel:false, notes:"Network of 200+ luxury builders" },

  // Additional confirmed locations from research
  { name:"PoolSupplies.com", company:"PoolSupplies.com", type:"online", category:"full-service", address:"574 Main St", city:"Tonawanda", state:"NY", zip:"14150", lat:43.014, lng:-78.883, phone:"800-772-0467", website:"poolsupplies.com", products:"Covers, Liners, Chemicals, Equipment", privateLabel:false, notes:"Independent since 1958. 245K sq ft facility. Online + print catalog." },
  { name:"Doheny's Pool Supplies HQ", company:"Doheny's", type:"online", category:"full-service", address:"10411 80th Ave", city:"Pleasant Prairie", state:"WI", zip:"53158", lat:42.542, lng:-87.843, phone:"800-574-7665", website:"doheny.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Family-owned since 1967. 9 warehouses (OH,PA,SC,FL,TN,IL,WI,TX,NV). Next-day delivery." },
  { name:"Anthony & Sylvan Pools - Doylestown", company:"Anthony & Sylvan", type:"independent", category:"full-service", address:"4371 County Line Rd", city:"Doylestown", state:"PA", zip:"18902", lat:40.323, lng:-75.113, phone:"215-489-0100", website:"anthonysylvan.com", products:"Pool construction, Chemicals, Equipment", privateLabel:true, notes:"HQ — 70+ years. ~20 design centers + 3 retail supply stores. East Coast." },
  { name:"Anthony & Sylvan Pools - Lancaster", company:"Anthony & Sylvan", type:"independent", category:"full-service", address:"2137 Embassy Dr", city:"Lancaster", state:"PA", zip:"17603", lat:40.020, lng:-76.350, phone:"717-397-1212", website:"anthonysylvan.com", products:"Pool construction, Chemicals, Equipment", privateLabel:true, notes:"Retail supply store" },
  { name:"Anthony & Sylvan Pools - Manalapan", company:"Anthony & Sylvan", type:"independent", category:"full-service", address:"340 US Route 9", city:"Manalapan", state:"NJ", zip:"07726", lat:40.285, lng:-74.305, phone:"732-792-2711", website:"anthonysylvan.com", products:"Pool construction, Chemicals, Equipment", privateLabel:true, notes:"Retail supply store" },
  { name:"Patio Pools - Sierra Vista", company:"Patio Pools", type:"independent", category:"full-service", address:"4148 Industry Dr Ste 1108", city:"Sierra Vista", state:"AZ", zip:"85635", lat:31.556, lng:-110.278, phone:"520-458-9291", website:"patiopoolsaz.com", products:"Equipment, Chemicals, Hot tubs, Service", privateLabel:false, notes:"50+ years. Authorized Hot Spring dealer." },
  { name:"Patio Pools - Oro Valley", company:"Patio Pools", type:"independent", category:"full-service", address:"7918 N Oracle Rd", city:"Oro Valley", state:"AZ", zip:"85704", lat:32.342, lng:-110.974, phone:"520-797-2299", website:"patiopoolsaz.com", products:"Equipment, Chemicals, Hot tubs, Service", privateLabel:false, notes:"Free water testing." },

  // Additional Heritage locations from 2024-2025 expansion
  { name:"Heritage Pool Supply - Sanford", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"3751 S Orlando Dr", city:"Sanford", state:"FL", zip:"32773", lat:28.779, lng:-81.294, phone:"407-322-0800", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"New location Feb 2025" },
  { name:"Heritage Pool Supply - San Diego", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"7340 Miramar Rd", city:"San Diego", state:"CA", zip:"92126", lat:32.893, lng:-117.150, phone:"858-549-1100", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"New location Mar 2025" },
  { name:"Heritage Pool Supply - Alpharetta", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"12770 Crabapple Rd", city:"Alpharetta", state:"GA", zip:"30004", lat:34.100, lng:-84.296, phone:"770-740-0700", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"New 2024 expansion" },
  { name:"Aqua-Gon Supply - Chicago", company:"Heritage Pool Supply", type:"wholesale", category:"full-service", address:"4700 W Lake St", city:"Chicago", state:"IL", zip:"60644", lat:41.887, lng:-87.744, phone:"773-379-3100", website:"heritagepoolsupplygroup.com", products:"Chemicals, Equipment, Parts", privateLabel:true, notes:"Aqua-Gon brand (Heritage subsidiary). Midwest." },

  // Additional Bullfrog factory stores
  { name:"Bullfrog Factory Store - Bluffdale", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"668 W 14600 S", city:"Bluffdale", state:"UT", zip:"84065", lat:40.489, lng:-111.937, phone:"801-553-8535", website:"bullfrogspas.com", products:"Hot tubs, JetPak systems", privateLabel:false, notes:"Factory store — direct" },
  { name:"Bullfrog Factory Store - Springville", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"1851 W 500 S Ste C-1", city:"Springville", state:"UT", zip:"84663", lat:40.154, lng:-111.639, phone:"801-491-3535", website:"bullfrogspas.com", products:"Hot tubs, JetPak systems", privateLabel:false, notes:"Factory store" },
  { name:"Bullfrog Factory Store - Billings", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"2950 King Ave W", city:"Billings", state:"MT", zip:"59102", lat:45.775, lng:-108.577, phone:"406-534-3535", website:"bullfrogspas.com", products:"Hot tubs, JetPak systems", privateLabel:false, notes:"Factory store" },
  { name:"Bullfrog Factory Store - Mooresville", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"168 Norman Station Blvd H", city:"Mooresville", state:"NC", zip:"28117", lat:35.592, lng:-80.831, phone:"704-799-3535", website:"bullfrogspas.com", products:"Hot tubs, JetPak systems", privateLabel:false, notes:"Factory store — SE market" },
  { name:"Bullfrog Factory Store - Cary", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"2450 Walnut St Ste 16", city:"Cary", state:"NC", zip:"27518", lat:35.755, lng:-78.749, phone:"919-535-3535", website:"bullfrogspas.com", products:"Hot tubs, JetPak systems", privateLabel:false, notes:"Factory store" },
  { name:"Bullfrog Factory Store - Rockford", company:"Bullfrog Spas", type:"manufacturer-dealer", category:"hot-tub", address:"5513 E State St", city:"Rockford", state:"IL", zip:"61108", lat:42.268, lng:-88.965, phone:"815-316-3535", website:"bullfrogspas.com", products:"Hot tubs, JetPak systems", privateLabel:false, notes:"Factory store — Midwest" },

  // Additional Jacuzzi confirmed locations
  { name:"Jacuzzi Hot Tubs of Charlotte", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"9522 E Independence Blvd", city:"Matthews", state:"NC", zip:"28105", lat:35.127, lng:-80.700, phone:"704-845-9000", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Jacuzzi Hot Tubs of the Triangle", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"124 Purfoy Rd", city:"Holly Springs", state:"NC", zip:"27540", lat:35.651, lng:-78.838, phone:"919-459-8800", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Twin City Jacuzzi", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"8100 Wayzata Blvd", city:"St Louis Park", state:"MN", zip:"55426", lat:44.960, lng:-93.362, phone:"952-835-4090", website:"jacuzzi.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"King Technology home market — MN" },
  { name:"Take A Break Spas - Jacuzzi", company:"Jacuzzi", type:"manufacturer-dealer", category:"hot-tub", address:"690 W Main St", city:"American Fork", state:"UT", zip:"84003", lat:40.375, lng:-111.803, phone:"801-756-4747", website:"jacuzzi.com", products:"Hot tubs, Billiards, Spa chemicals", privateLabel:false, notes:"" },

  // Additional Hot Spring confirmed locations
  { name:"Creative Energy - San Mateo", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"2245 S El Camino Real", city:"San Mateo", state:"CA", zip:"94403", lat:37.540, lng:-122.315, phone:"650-345-7800", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"4 CA locations. Pentair/Watkins dealer." },
  { name:"American Sale - Naperville", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"1200 E Ogden Ave", city:"Naperville", state:"IL", zip:"60563", lat:41.775, lng:-88.128, phone:"630-355-5700", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"8 IL locations" },
  { name:"Hot Spring Spas of KC", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"11110 W 75th St", city:"Shawnee", state:"KS", zip:"66214", lat:38.969, lng:-94.741, phone:"913-268-5900", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"" },
  { name:"Spas Etc - Orlando", company:"Hot Spring Spas", type:"manufacturer-dealer", category:"hot-tub", address:"5621 S Orange Blossom Trail", city:"Orlando", state:"FL", zip:"32839", lat:28.477, lng:-81.403, phone:"407-857-4447", website:"hotspring.com", products:"Hot tubs, Spa chemicals", privateLabel:false, notes:"Also serves Daytona" },

  // ═══════════════════════════════════════════════════════════
  // BIG BOX / MASS RETAIL — Pool chemical sections
  // ═══════════════════════════════════════════════════════════
  { name:"Home Depot - Pool Section (representative)", company:"Home Depot", type:"big-box", category:"chemicals", address:"2455 Paces Ferry Rd", city:"Atlanta", state:"GA", zip:"30339", lat:33.887, lng:-84.467, phone:"770-433-8211", website:"homedepot.com", products:"Chemicals, Basic equipment, Accessories", privateLabel:true, notes:"2,300+ US stores — HDX private label chemicals. Acquiring Heritage Pool Supply." },
  { name:"Lowe's - Pool Section (representative)", company:"Lowe's", type:"big-box", category:"chemicals", address:"1000 Lowes Blvd", city:"Mooresville", state:"NC", zip:"28117", lat:35.591, lng:-80.831, phone:"704-758-1000", website:"lowes.com", products:"Chemicals, Basic equipment", privateLabel:true, notes:"1,700+ US stores — carries major chemical brands" },
  { name:"Walmart - Pool Section (representative)", company:"Walmart", type:"big-box", category:"chemicals", address:"702 SW 8th St", city:"Bentonville", state:"AR", zip:"72712", lat:36.370, lng:-94.209, phone:"479-273-4000", website:"walmart.com", products:"Chemicals, Basic accessories", privateLabel:true, notes:"4,700+ US stores — Clorox Pool & Spa brand" },
  { name:"Costco - Pool Section (representative)", company:"Costco", type:"big-box", category:"chemicals", address:"999 Lake Dr", city:"Issaquah", state:"WA", zip:"98027", lat:47.546, lng:-122.064, phone:"425-313-8100", website:"costco.com", products:"Bulk chemicals, Basic equipment", privateLabel:true, notes:"600+ US warehouses — Kirkland/bulk chemicals" },
  { name:"Ace Hardware - Pool Section (representative)", company:"Ace Hardware", type:"big-box", category:"chemicals", address:"2200 Kensington Ct", city:"Oak Brook", state:"IL", zip:"60523", lat:41.843, lng:-87.939, phone:"630-990-6600", website:"acehardware.com", products:"Chemicals, Basic accessories, Test kits", privateLabel:false, notes:"~4,800-5,200 US stores — carries HTH, BioGuard, Clorox. Strongest pool sections in Sun Belt." },
  { name:"True Value / Do it Best - Pool Section (representative)", company:"True Value", type:"big-box", category:"chemicals", address:"233 S Wacker Dr", city:"Chicago", state:"IL", zip:"60606", lat:41.878, lng:-87.636, phone:"773-695-5000", website:"truevalue.com", products:"Chemicals, Test kits, Maintenance equipment", privateLabel:false, notes:"~4,500 US stores. Merged with Do it Best (2024). Carries national brands." },

  // ═══════════════════════════════════════════════════════════
  // NATURAL CHEMISTRY — Chemical competitor
  // ═══════════════════════════════════════════════════════════
  { name:"Natural Chemistry HQ", company:"Natural Chemistry", type:"manufacturer-dealer", category:"chemicals", address:"1 Willard Rd", city:"Norwalk", state:"CT", zip:"06851", lat:41.110, lng:-73.420, phone:"203-295-2300", website:"naturalchemistry.com", products:"Enzyme-based pool/spa chemicals", privateLabel:false, notes:"Enzyme-based specialty — competes in 'natural' segment with King" },

];

// ═══════════════════════════════════════════════════════════
// Color palette for dealer types and companies
// ═══════════════════════════════════════════════════════════
const COMPANY_COLORS = {
  "PoolCorp":           "#e74c3c", // Red — primary threat
  "Heritage Pool Supply":"#e67e22", // Orange — #2 threat
  "Leslie's":           "#f1c40f", // Yellow
  "Pinch A Penny":      "#2ecc71", // Green
  "Hayward":            "#9b59b6", // Purple
  "Pentair":            "#3498db", // Blue
  "Fluidra/Zodiac":     "#1abc9c", // Teal
  "BioGuard":           "#e91e63", // Pink — chemical competitor
  "King Technology":    "#00ff88", // Bright green — SUBJECT
  "Hot Spring Spas":    "#ff9800", // Amber
  "Jacuzzi":            "#00bcd4", // Cyan
  "Bullfrog Spas":      "#8bc34a", // Light green
  "Sundance Spas":      "#ff5722", // Deep orange
  "Home Depot":         "#ff6f00", // HD Orange
  "Lowe's":             "#1565c0", // Lowe's Blue
  "Walmart":            "#0071ce", // Walmart Blue
  "Costco":             "#e31837", // Costco Red
  "Ace Hardware":       "#d32f2f", // Ace Red
  "Natural Chemistry":  "#7e57c2", // Purple
  "ASP":                "#546e7a", // Blue-grey
  "Master Pools Guild": "#78909c", // Grey-blue
  "True Value":         "#228b22", // Forest green
  "PoolSupplies.com":   "#ba68c8", // Light purple
  "Patio Pools":        "#26a69a", // Teal
  "Anthony & Sylvan":   "#5c6bc0", // Indigo
};

const TYPE_COLORS = {
  "wholesale":          "#e74c3c",
  "retail-chain":       "#f1c40f",
  "franchise":          "#2ecc71",
  "independent":        "#3498db",
  "online":             "#9b59b6",
  "big-box":            "#ff9800",
  "manufacturer-dealer":"#e91e63",
};

const TYPE_LABELS = {
  "wholesale":          "Wholesale Distributor",
  "retail-chain":       "Retail Chain",
  "franchise":          "Franchise",
  "independent":        "Independent Dealer",
  "online":             "Online Retailer",
  "big-box":            "Big Box / Mass Retail",
  "manufacturer-dealer":"Manufacturer / Dealer Network",
};

// State data for combobox
const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA",
  "KS","KY","LA","MA","MD","ME","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
  "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT",
  "VA","WA","WV","WI","WY"
];
